mode:
  type: Standalone
  repository:
    type: JDBC

authority:
  users:
    - user: test_user@%
      password: password123
  privilege:
    type: ALL_PERMITTED

sqlFederation:
  sqlFederationEnabled: true
  executionPlanCache:
    initialCapacity: 2000
    maximumSize: 65535

props:
  max-connections-size-per-query: 15
  kernel-executor-size: 0 # Infinite by default.
  proxy-frontend-flush-threshold: 128 # The default value is 128.
  proxy-hint-enabled: false
  sql-show: true
  check-table-metadata-enabled: true
  # Proxy backend query fetch size. A larger value may increase the memory usage of ShardingSphere Proxy.
  # The default value is -1, which means set the minimum value for different JDBC drivers.
  proxy-backend-query-fetch-size: -1
  proxy-frontend-executor-size: 0 # Proxy frontend executor size. The default value is 0, which means let Netty decide.
  # Available options of proxy backend executor suitable: OLAP(default), OLTP. The OLTP option may reduce time cost of writing packets to client, but it may increase the latency of SQL execution
  # and block other clients if client connections are more than `proxy-frontend-executor-size`, especially executing slow SQL.
  proxy-backend-executor-suitable: OLAP
  proxy-frontend-max-connections: 0 # Less than or equal to 0 means no limitation.
  # Available sql federation type: NONE (default), ORIGINAL, ADVANCED
  sql-federation-type: NONE
  # Available proxy backend driver type: JDBC (default), ExperimentalVertx
  proxy-backend-driver-type: JDBC
  proxy-mysql-default-version: 8 # In the absence of schema name, the default version will be used.
  proxy-default-port: 3306 # Proxy default port.
  proxy-netty-backlog: 1024 # Proxy netty backlog.
  proxy-frontend-ssl-enabled: true
  proxy-frontend-ssl-cipher: ''
  proxy-frontend-ssl-version: TLSv1.2,TLSv1.3
